name: Release App

on:
  push:
    tags:
      - 'v*' # 当推送以 v 开头的 tag 时触发，例如 v1.0.1, v1.0.2

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller builderTool.spec

      - name: Rename EXE
        shell: pwsh
        run: |
          # 将生成的 exe 备份并复制为带版本号的格式
          Copy-Item -Path .\dist\builderTool.exe -Destination .\dist\builderTool-${{ github.ref_name }}.exe -Force

      - name: Extract Release Notes from README
        run: |
          python extract_changelog.py "${{ github.ref_name }}"

      - name: Create or Update Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} dist/builderTool-${{ github.ref_name }}.exe --title "${{ github.ref_name }}" --notes-file RELEASE_NOTES.md --clobber
